Repository dnd-side-project/dnd-11th-8-backend, pull requests merged in 2024-08, with the labels that each got.

#25 [BLOOM-008] 카카오 OIDC 로그인 구현
  build.gradle.kts
  src/main/kotlin/dnd11th/blooming/Dnd11th8BackendApplication.kt
  src/main/kotlin/dnd11th/blooming/api/controller/UserController.kt
  src/main/kotlin/dnd11th/blooming/api/controller/user/UserController.kt
  src/main/kotlin/dnd11th/blooming/api/controller/user/UserLoginController.kt
  src/main/kotlin/dnd11th/blooming/api/dto/user/IdTokenRequest.kt
  src/main/kotlin/dnd11th/blooming/api/dto/user/TokenResponse.kt
  src/main/kotlin/dnd11th/blooming/api/service/user/SocialLoginService.kt
  src/main/kotlin/dnd11th/blooming/api/service/user/oauth/KakaoIdTokenResolver.kt
  src/main/kotlin/dnd11th/blooming/api/service/user/oauth/KakaoOauthProperties.kt
  src/main/kotlin/dnd11th/blooming/api/service/user/oauth/OpenIdTokenResolver.kt
  src/main/kotlin/dnd11th/blooming/client/KakaoOauthClient.kt
  src/main/kotlin/dnd11th/blooming/client/config/FeignClientConfig.kt
  src/main/kotlin/dnd11th/blooming/client/dto/OidcPublicKey.kt
  src/main/kotlin/dnd11th/blooming/client/dto/OidcPublicKeys.kt
  src/main/kotlin/dnd11th/blooming/common/exception/BadRequestException.kt
  src/main/kotlin/dnd11th/blooming/common/exception/ErrorType.kt
  src/main/kotlin/dnd11th/blooming/common/exception/UnAuthorizedException.kt
  src/main/kotlin/dnd11th/blooming/common/interceptor/AuthInterceptor.kt
  src/main/kotlin/dnd11th/blooming/common/jwt/JwtConfig.kt
  src/main/kotlin/dnd11th/blooming/common/jwt/JwtProperties.kt
  src/main/kotlin/dnd11th/blooming/common/jwt/JwtProvider.kt
  src/main/kotlin/dnd11th/blooming/common/resolver/LoginUserArgumentResolver.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/Location.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/MyPlant.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/user/OauthProvider.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/user/OidcUser.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/user/User.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/user/UserClaims.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/user/UserOauthInfo.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/user/UserOauthRepository.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/user/UserRepository.kt
  src/main/resources/application.yml
  src/test/kotlin/dnd11th/blooming/common/jwt/JwtProviderTest.kt
  src/test/resources/application-test.yml
Labels: 🌱 feat

#29 [BLOOM-26] Swagger 설정
  build.gradle.kts
  src/main/kotlin/dnd11th/blooming/api/config/SwaggerConfig.kt
  src/main/kotlin/dnd11th/blooming/api/controller/HealthApi.kt
  src/main/kotlin/dnd11th/blooming/api/controller/HealthController.kt
  src/main/kotlin/dnd11th/blooming/api/service/user/oauth/KakaoOauthProperties.kt
  src/main/kotlin/dnd11th/blooming/common/annotation/ApiErrorResponse.kt
  src/main/kotlin/dnd11th/blooming/common/annotation/ApiErrorResponses.kt
  src/main/kotlin/dnd11th/blooming/common/exception/ErrorType.kt
  src/main/kotlin/dnd11th/blooming/common/jwt/JwtProperties.kt
  src/main/resources/application.yml
Labels: 🌱 feat

#31 [BLOOM-027] 식물 api 수정 및 추가
  src/main/kotlin/dnd11th/blooming/api/controller/MyPlantController.kt
  src/main/kotlin/dnd11th/blooming/api/controller/home/HomeController.kt
  src/main/kotlin/dnd11th/blooming/api/controller/location/LocationController.kt
  src/main/kotlin/dnd11th/blooming/api/controller/myplant/MyPlantController.kt
  src/main/kotlin/dnd11th/blooming/api/dto/AlarmModifyRequest.kt
  src/main/kotlin/dnd11th/blooming/api/dto/AlarmResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/MyPlantDetailResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/home/HomeResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/home/MyPlantHomeResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/location/LocationModifyRequest.kt
  src/main/kotlin/dnd11th/blooming/api/dto/location/LocationResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/location/LocationSaveRequest.kt
  src/main/kotlin/dnd11th/blooming/api/dto/location/LocationSaveResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/AlarmModifyRequest.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantDetailResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantDirectionParam.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantHealthCheckRequest.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantModifyRequest.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantQueryCreteria.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantSaveRequest.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantSaveResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantSortParam.kt
  src/main/kotlin/dnd11th/blooming/api/service/MyPlantService.kt
  src/main/kotlin/dnd11th/blooming/api/service/home/HomeService.kt
  src/main/kotlin/dnd11th/blooming/api/service/location/LocationService.kt
  src/main/kotlin/dnd11th/blooming/api/service/myplant/MyPlantMessageFactory.kt
  src/main/kotlin/dnd11th/blooming/api/service/myplant/MyPlantService.kt
  src/main/kotlin/dnd11th/blooming/common/exception/ErrorType.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/Alarm.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/MyPlant.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/LocationRepository.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/MyPlantRepository.kt
  src/test/kotlin/dnd11th/blooming/api/PlantControllerTest.kt
  src/test/kotlin/dnd11th/blooming/api/controller/home/HomeControllerTest.kt
  src/test/kotlin/dnd11th/blooming/api/controller/location/LocationControllerTest.kt
  src/test/kotlin/dnd11th/blooming/api/controller/myplant/MyPlantControllerTest.kt
  src/test/kotlin/dnd11th/blooming/api/service/home/HomeServiceTest.kt
  src/test/kotlin/dnd11th/blooming/api/service/location/LocationServiceTest.kt
  src/test/kotlin/dnd11th/blooming/api/service/myplant/MyPlantServiceTest.kt
  src/test/kotlin/dnd11th/blooming/domain/entity/MyPlantTest.kt
  src/test/kotlin/dnd11th/blooming/service/PlantServiceTest.kt
Labels: 🌱 feat, 🔨 fix

#32 [BLOOM-030] 날씨에 맞는 식물 관리법 조회 API
  src/main/kotlin/dnd11th/blooming/api/controller/weather/WeatherMessageController.kt
  src/main/kotlin/dnd11th/blooming/api/dto/weather/WeatherMessageResponse.kt
  src/main/kotlin/dnd11th/blooming/api/service/user/oauth/KakaoIdTokenResolver.kt
  src/main/kotlin/dnd11th/blooming/api/service/weather/WeatherMessage.kt
  src/main/kotlin/dnd11th/blooming/api/service/weather/WeatherService.kt
  src/main/kotlin/dnd11th/blooming/client/dto/WeatherResponse.kt
  src/main/kotlin/dnd11th/blooming/client/kakao/KakaoOauthClient.kt
  src/main/kotlin/dnd11th/blooming/client/weather/WeatherInfoClient.kt
  src/main/kotlin/dnd11th/blooming/common/exception/ClientCallException.kt
  src/main/kotlin/dnd11th/blooming/common/exception/ErrorType.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/user/User.kt
  src/main/resources/application.yml
  src/test/resources/application-test.yml
Labels: 🌱 feat

#38 [BLOOM-037] 기본 profile local 설정
  src/main/resources/application.yml
Labels: 💊 refactor

#45 [BLOOM-044] 날씨 메시지 API Swagger 문서화
  src/main/kotlin/dnd11th/blooming/api/controller/weather/WeatherMessageApi.kt
  src/main/kotlin/dnd11th/blooming/api/controller/weather/WeatherMessageController.kt
  src/main/kotlin/dnd11th/blooming/api/dto/weather/WeatherMessageResponse.kt
  src/main/kotlin/dnd11th/blooming/common/exception/ErrorType.kt
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: 📚 docs

#47 [BLOOM-043] 내식물, 위치, 홈화면, 이미지 관련 api에 swagger 문서화 적용
  src/main/kotlin/dnd11th/blooming/api/controller/HealthApi.kt
  src/main/kotlin/dnd11th/blooming/api/controller/home/HomeApi.kt
  src/main/kotlin/dnd11th/blooming/api/controller/home/HomeController.kt
  src/main/kotlin/dnd11th/blooming/api/controller/image/ImageApi.kt
  src/main/kotlin/dnd11th/blooming/api/controller/image/ImageController.kt
  src/main/kotlin/dnd11th/blooming/api/controller/location/LocationApi.kt
  src/main/kotlin/dnd11th/blooming/api/controller/location/LocationController.kt
  src/main/kotlin/dnd11th/blooming/api/controller/myplant/MyPlantApi.kt
  src/main/kotlin/dnd11th/blooming/api/controller/myplant/MyPlantController.kt
  src/main/kotlin/dnd11th/blooming/api/dto/home/HomeResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/home/MyPlantHomeResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/image/ImageFavoriteModifyRequest.kt
  src/main/kotlin/dnd11th/blooming/api/dto/image/ImageResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/image/ImageSaveRequest.kt
  src/main/kotlin/dnd11th/blooming/api/dto/location/LocationModifyRequest.kt
  src/main/kotlin/dnd11th/blooming/api/dto/location/LocationResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/location/LocationSaveRequest.kt
  src/main/kotlin/dnd11th/blooming/api/dto/location/LocationSaveResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/AlarmModifyRequest.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantDetailResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantHealthCheckRequest.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantModifyRequest.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantSaveRequest.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantSaveResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/weather/WeatherMessageResponse.kt
  src/main/kotlin/dnd11th/blooming/common/exception/ErrorType.kt
Labels: 📚 docs

#48 [BLOOM-041] validation 추가, api 마이너 수정 #46
  build.gradle.kts
  src/main/kotlin/dnd11th/blooming/api/controller/image/ImageController.kt
  src/main/kotlin/dnd11th/blooming/api/controller/location/LocationController.kt
  src/main/kotlin/dnd11th/blooming/api/controller/myplant/MyPlantController.kt
  src/main/kotlin/dnd11th/blooming/api/controller/user/UserController.kt
  src/main/kotlin/dnd11th/blooming/api/dto/home/HomeResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/home/MyPlantHomeResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/image/ImageCreateDto.kt
  src/main/kotlin/dnd11th/blooming/api/dto/image/ImageFavoriteModifyRequest.kt
  src/main/kotlin/dnd11th/blooming/api/dto/image/ImageResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/image/ImageSaveRequest.kt
  src/main/kotlin/dnd11th/blooming/api/dto/location/LocationCreateDto.kt
  src/main/kotlin/dnd11th/blooming/api/dto/location/LocationModifyRequest.kt
  src/main/kotlin/dnd11th/blooming/api/dto/location/LocationResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/location/LocationSaveRequest.kt
  src/main/kotlin/dnd11th/blooming/api/dto/location/LocationSaveResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/AlarmModifyRequest.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantCreateDto.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantHealthCheckRequest.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantIdWithImageUrl.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantModifyRequest.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantSaveRequest.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantSaveResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/user/IdTokenRequest.kt
  src/main/kotlin/dnd11th/blooming/api/service/image/ImageService.kt
  src/main/kotlin/dnd11th/blooming/api/service/location/LocationService.kt
  src/main/kotlin/dnd11th/blooming/api/service/myplant/MyPlantService.kt
  src/main/kotlin/dnd11th/blooming/common/exception/ErrorResponse.kt
  src/main/kotlin/dnd11th/blooming/common/exception/ErrorType.kt
  src/main/kotlin/dnd11th/blooming/common/exception/FieldErrorResponse.kt
  src/main/kotlin/dnd11th/blooming/common/exception/GlobalExceptionHandler.kt
  src/main/kotlin/dnd11th/blooming/common/exception/InvalidDateException.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/BaseEntity.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/Image.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/Location.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/MyPlant.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/user/User.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/user/UserOauthInfo.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/ImageRepository.kt
  src/test/kotlin/dnd11th/blooming/api/controller/home/HomeControllerTest.kt
  src/test/kotlin/dnd11th/blooming/api/controller/image/ImageControllerValidationTest.kt
  src/test/kotlin/dnd11th/blooming/api/controller/location/LocationControllerTest.kt
  src/test/kotlin/dnd11th/blooming/api/controller/location/LocationControllerValidationTest.kt
  src/test/kotlin/dnd11th/blooming/api/controller/myplant/MyPlantControllerTest.kt
  src/test/kotlin/dnd11th/blooming/api/controller/myplant/MyPlantControllerValidationTest.kt
  src/test/kotlin/dnd11th/blooming/api/service/home/HomeServiceTest.kt
  src/test/kotlin/dnd11th/blooming/api/service/location/LocationServiceTest.kt
  src/test/kotlin/dnd11th/blooming/api/service/myplant/MyPlantServiceIntegrationTest.kt
  src/test/kotlin/dnd11th/blooming/api/service/myplant/MyPlantServiceTest.kt
Labels: 🌱 feat, 🔨 fix, 📚 docs

#54 [BLOOM-042] 회원가입 시 기본 식물 위치 제공
  src/main/kotlin/dnd11th/blooming/api/service/user/UserRegisterService.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/Location.kt
Labels: 🧹 chore

#56 [BLOOM-030] 행정구역 검색 API
  src/main/kotlin/dnd11th/blooming/api/controller/region/RegionController.kt
  src/main/kotlin/dnd11th/blooming/api/controller/user/UserController.kt
  src/main/kotlin/dnd11th/blooming/api/dto/region/RegionResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/user/MyProfileResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/user/UserRegisterRequest.kt
  src/main/kotlin/dnd11th/blooming/api/service/region/RegionService.kt
  src/main/kotlin/dnd11th/blooming/api/service/user/UserProfileService.kt
  src/main/kotlin/dnd11th/blooming/api/service/user/UserRegisterService.kt
  src/main/kotlin/dnd11th/blooming/common/resolver/LoginUserArgumentResolver.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/region/CityProvince.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/region/Region.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/region/SiGunGu.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/user/User.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/user/UserRegisterInfo.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/MyPlantRepository.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/region/RegionRepository.kt
  src/test/kotlin/dnd11th/blooming/api/controller/home/HomeControllerTest.kt
  src/test/kotlin/dnd11th/blooming/api/controller/image/ImageControllerValidationTest.kt
  src/test/kotlin/dnd11th/blooming/api/controller/location/LocationControllerTest.kt
  src/test/kotlin/dnd11th/blooming/api/controller/location/LocationControllerValidationTest.kt
  src/test/kotlin/dnd11th/blooming/api/controller/myplant/MyPlantControllerTest.kt
  src/test/kotlin/dnd11th/blooming/api/controller/myplant/MyPlantControllerValidationTest.kt
Labels: 🌱 feat, 💊 refactor

#60 [BLOOM-059] deploy.yml 수정
  .github/workflows/deploy.yml
Labels: 🔨 fix

#61 [BLOOM-057] WebMvc 환경 통합 및 Test 환경 구성
  src/test/kotlin/dnd11th/blooming/api/controller/home/HomeControllerTest.kt
  src/test/kotlin/dnd11th/blooming/api/controller/image/ImageControllerValidationTest.kt
  src/test/kotlin/dnd11th/blooming/api/controller/location/LocationControllerTest.kt
  src/test/kotlin/dnd11th/blooming/api/controller/location/LocationControllerValidationTest.kt
  src/test/kotlin/dnd11th/blooming/api/controller/myplant/MyPlantControllerTest.kt
  src/test/kotlin/dnd11th/blooming/api/controller/myplant/MyPlantControllerValidationTest.kt
  src/test/kotlin/dnd11th/blooming/support/StubAuthInterceptor.kt
  src/test/kotlin/dnd11th/blooming/support/StubHandlerArgumentResolver.kt
  src/test/kotlin/dnd11th/blooming/support/TestWebMvcConfig.kt
  src/test/kotlin/dnd11th/blooming/support/WebMvcDescribeSpec.kt
Labels: 💊 refactor, 🧽 test

#63 [BLOOM-062] RefreshToken을 통한 재발급 기능 구현
  src/main/kotlin/dnd11th/blooming/api/controller/user/TokenController.kt
  src/main/kotlin/dnd11th/blooming/api/dto/user/IdTokenRequest.kt
  src/main/kotlin/dnd11th/blooming/api/dto/user/MyProfileResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/user/SocialLoginResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/user/TokenRequest.kt
  src/main/kotlin/dnd11th/blooming/api/dto/user/TokenResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/user/UserRegisterRequest.kt
  src/main/kotlin/dnd11th/blooming/api/service/user/SocialLoginService.kt
  src/main/kotlin/dnd11th/blooming/api/service/user/TokenService.kt
  src/main/kotlin/dnd11th/blooming/api/service/user/UserRegisterService.kt
  src/main/kotlin/dnd11th/blooming/common/jwt/JwtProvider.kt
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: 🌱 feat

#53 [BLOOM-051] 식물 가이드 api 개발, 기존 api 수정
  src/main/kotlin/dnd11th/blooming/api/controller/guide/GuideApi.kt
  src/main/kotlin/dnd11th/blooming/api/controller/guide/GuideController.kt
  src/main/kotlin/dnd11th/blooming/api/controller/location/LocationApi.kt
  src/main/kotlin/dnd11th/blooming/api/controller/location/LocationController.kt
  src/main/kotlin/dnd11th/blooming/api/controller/myplant/MyPlantApi.kt
  src/main/kotlin/dnd11th/blooming/api/controller/myplant/MyPlantController.kt
  src/main/kotlin/dnd11th/blooming/api/dto/guide/PlantGuideResponses.kt
  src/main/kotlin/dnd11th/blooming/api/dto/guide/PlantRecommendedPeriodResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/guide/PlantResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/home/MyPlantHomeResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/location/MyPlantExistInLocationResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantCreateDto.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantDetailResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantHealthCheckRequest.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantSaveRequest.kt
  src/main/kotlin/dnd11th/blooming/api/service/guide/GuideService.kt
  src/main/kotlin/dnd11th/blooming/api/service/guide/PlantMessageFactory.kt
  src/main/kotlin/dnd11th/blooming/api/service/guide/StaticPlantMessageFactory.kt
  src/main/kotlin/dnd11th/blooming/api/service/guide/provider/HumidityDetailProvider.kt
  src/main/kotlin/dnd11th/blooming/api/service/guide/provider/LightDetailProvider.kt
  src/main/kotlin/dnd11th/blooming/api/service/guide/provider/PestsDetailProvider.kt
  src/main/kotlin/dnd11th/blooming/api/service/guide/provider/StaticPlantDetailMessageProvider.kt
  src/main/kotlin/dnd11th/blooming/api/service/guide/provider/StaticPlantSimpleMessageProvider.kt
  src/main/kotlin/dnd11th/blooming/api/service/guide/provider/ToxicityDetailProvider.kt
  src/main/kotlin/dnd11th/blooming/api/service/guide/provider/WaterDetailProvider.kt
  src/main/kotlin/dnd11th/blooming/api/service/location/LocationService.kt
  src/main/kotlin/dnd11th/blooming/api/service/myplant/MyPlantService.kt
  src/main/kotlin/dnd11th/blooming/common/exception/ErrorType.kt
  src/main/kotlin/dnd11th/blooming/common/util/KoreanUtil.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/Illust.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/MyPlant.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/plant/Difficulty.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/plant/Fertilizer.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/plant/GrowLocation.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/plant/GrowTemperature.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/plant/Humidity.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/plant/Light.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/plant/LowestTemperature.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/plant/Plant.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/plant/Season.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/plant/Toxicity.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/plant/Water.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/ImageRepository.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/MyPlantRepository.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/PlantRepository.kt
  src/test/kotlin/dnd11th/blooming/api/controller/home/HomeControllerTest.kt
  src/test/kotlin/dnd11th/blooming/api/controller/myplant/MyPlantControllerTest.kt
  src/test/kotlin/dnd11th/blooming/api/controller/myplant/MyPlantControllerValidationTest.kt
  src/test/kotlin/dnd11th/blooming/api/service/home/HomeServiceTest.kt
  src/test/kotlin/dnd11th/blooming/api/service/location/LocationServiceTest.kt
  src/test/kotlin/dnd11th/blooming/api/service/myplant/MyPlantServiceIntegrationTest.kt
  src/test/kotlin/dnd11th/blooming/api/service/myplant/MyPlantServiceTest.kt
  src/test/kotlin/dnd11th/blooming/domain/entity/MyPlantTest.kt
Labels: 🌱 feat, 🔨 fix

#65 [BLOOM-064] 마이페이지 수정 API 구현
  src/main/kotlin/dnd11th/blooming/api/controller/user/UserController.kt
  src/main/kotlin/dnd11th/blooming/api/dto/user/MyProfileUpdateRequest.kt
  src/main/kotlin/dnd11th/blooming/api/service/user/UserProfileService.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/user/User.kt
Labels: 🌱 feat

#66 [BLOOM-055] LoginUser, Secured 적용
  src/main/kotlin/dnd11th/blooming/api/controller/home/HomeApi.kt
  src/main/kotlin/dnd11th/blooming/api/controller/home/HomeController.kt
  src/main/kotlin/dnd11th/blooming/api/controller/image/ImageApi.kt
  src/main/kotlin/dnd11th/blooming/api/controller/image/ImageController.kt
  src/main/kotlin/dnd11th/blooming/api/controller/location/LocationApi.kt
  src/main/kotlin/dnd11th/blooming/api/controller/location/LocationController.kt
  src/main/kotlin/dnd11th/blooming/api/controller/myplant/MyPlantApi.kt
  src/main/kotlin/dnd11th/blooming/api/controller/myplant/MyPlantController.kt
  src/main/kotlin/dnd11th/blooming/api/service/home/HomeService.kt
  src/main/kotlin/dnd11th/blooming/api/service/image/ImageService.kt
  src/main/kotlin/dnd11th/blooming/api/service/location/LocationService.kt
  src/main/kotlin/dnd11th/blooming/api/service/myplant/MyPlantService.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/Location.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/MyPlant.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/ImageRepository.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/LocationRepository.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/MyPlantRepository.kt
  src/test/kotlin/dnd11th/blooming/api/controller/home/HomeControllerTest.kt
  src/test/kotlin/dnd11th/blooming/api/controller/location/LocationControllerTest.kt
  src/test/kotlin/dnd11th/blooming/api/controller/myplant/MyPlantControllerTest.kt
  src/test/kotlin/dnd11th/blooming/api/service/home/HomeServiceTest.kt
  src/test/kotlin/dnd11th/blooming/api/service/location/LocationServiceTest.kt
  src/test/kotlin/dnd11th/blooming/api/service/myplant/MyPlantServiceIntegrationTest.kt
  src/test/kotlin/dnd11th/blooming/api/service/myplant/MyPlantServiceTest.kt
Labels: 🌱 feat

#68 [BLOOM-067] 내 식물, 위치 관련 api 수정
  build.gradle.kts
  src/main/kotlin/dnd11th/blooming/api/controller/location/LocationApi.kt
  src/main/kotlin/dnd11th/blooming/api/controller/location/LocationController.kt
  src/main/kotlin/dnd11th/blooming/api/controller/myplant/MyPlantApi.kt
  src/main/kotlin/dnd11th/blooming/api/controller/myplant/MyPlantController.kt
  src/main/kotlin/dnd11th/blooming/api/dto/image/ImageResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/HealthCheckResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantCreateDto.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantDetailResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantDirectionParam.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantQueryCreteria.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantSaveRequest.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantSaveResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantSortParam.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantWithImageUrl.kt
  src/main/kotlin/dnd11th/blooming/api/service/home/HomeService.kt
  src/main/kotlin/dnd11th/blooming/api/service/image/ImageService.kt
  src/main/kotlin/dnd11th/blooming/api/service/location/LocationService.kt
  src/main/kotlin/dnd11th/blooming/api/service/myplant/MyPlantMessageFactory.kt
  src/main/kotlin/dnd11th/blooming/api/service/myplant/MyPlantService.kt
  src/main/kotlin/dnd11th/blooming/api/service/user/UserProfileService.kt
  src/main/kotlin/dnd11th/blooming/api/service/user/UserRegisterService.kt
  src/main/kotlin/dnd11th/blooming/common/exception/ErrorType.kt
  src/main/kotlin/dnd11th/blooming/domain/config/QueryDslConfig.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/Location.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/MyPlant.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/ImageRepository.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/LocationRepository.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/MyPlantRepository.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/myplant/MyPlantQueryDslRepository.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/myplant/MyPlantQueryDslRepositoryImpl.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/myplant/MyPlantRepository.kt
  src/test/kotlin/dnd11th/blooming/api/controller/myplant/MyPlantControllerTest.kt
  src/test/kotlin/dnd11th/blooming/api/controller/myplant/MyPlantControllerValidationTest.kt
  src/test/kotlin/dnd11th/blooming/api/service/home/HomeServiceTest.kt
  src/test/kotlin/dnd11th/blooming/api/service/location/LocationServiceTest.kt
  src/test/kotlin/dnd11th/blooming/api/service/myplant/MyPlantServiceIntegrationTest.kt
  src/test/kotlin/dnd11th/blooming/api/service/myplant/MyPlantServiceTest.kt
Labels: 🔨 fix

#71 [BLOOM-069] Logger 전역 등록
  build.gradle.kts
  src/main/kotlin/dnd11th/blooming/common/exception/GlobalExceptionHandler.kt
  src/main/kotlin/dnd11th/blooming/common/util/Logger.kt
Labels: 🌱 feat

#74 [BLOOM-073] CORS 설정
  src/main/kotlin/dnd11th/blooming/api/config/WebMvcConfig.kt
  src/main/kotlin/dnd11th/blooming/api/config/properties/CorsProperties.kt
  src/main/kotlin/dnd11th/blooming/common/interceptor/AuthInterceptor.kt
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/test/resources/application-test.yml
Labels: 🌱 feat

#70 [BLOOM-058] FCM 알림 인터페이스 구현
  .github/workflows/deploy.yml
  .gitignore
  build.gradle.kts
  src/main/kotlin/dnd11th/blooming/api/service/user/oauth/AppleIdTokenResolver.kt
  src/main/kotlin/dnd11th/blooming/api/service/user/oauth/IdTokenProcessor.kt
  src/main/kotlin/dnd11th/blooming/api/service/user/oauth/IdTokenValidator.kt
  src/main/kotlin/dnd11th/blooming/api/service/user/oauth/KakaoIdTokenResolver.kt
  src/main/kotlin/dnd11th/blooming/api/service/user/oauth/PublicKeyGenerator.kt
  src/main/kotlin/dnd11th/blooming/api/service/weather/WeatherService.kt
  src/main/kotlin/dnd11th/blooming/client/config/FcmConfig.kt
  src/main/kotlin/dnd11th/blooming/client/fcm/FcmService.kt
  src/main/kotlin/dnd11th/blooming/client/fcm/FcmServiceImpl.kt
  src/main/kotlin/dnd11th/blooming/client/fcm/PushNotification.kt
  src/main/kotlin/dnd11th/blooming/client/oauth/AppleOauthClient.kt
  src/main/kotlin/dnd11th/blooming/client/oauth/KakaoOauthClient.kt
  src/main/kotlin/dnd11th/blooming/client/oauth/OidcPublicKey.kt
  src/main/kotlin/dnd11th/blooming/client/oauth/OidcPublicKeys.kt
  src/main/kotlin/dnd11th/blooming/client/weather/WeatherInfoClient.kt
  src/main/kotlin/dnd11th/blooming/client/weather/WeatherResponse.kt
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/test/kotlin/dnd11th/blooming/support/MockFcmConfig.kt
Labels: 🌱 feat

#76 [BLOOM-075] deploy 시 firebase json 파일 생성 fix
  .github/workflows/deploy.yml
Labels: 🔨 fix

#79 [BLOOM-077] Enum 값 추가
  src/main/kotlin/dnd11th/blooming/api/service/guide/provider/StaticPlantSimpleMessageProvider.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/plant/Difficulty.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/plant/Fertilizer.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/plant/GrowTemperature.kt
Labels: 🔨 fix

#81 [BLOOM-080] Plant Entity에서 BaseEntity와의 상속관계 제거
  src/main/kotlin/dnd11th/blooming/domain/entity/plant/Plant.kt
Labels: 💊 refactor

#82 [BLOOM-077] 식물 물주기 방법 분리
  src/main/kotlin/dnd11th/blooming/api/dto/guide/PlantRecommendedPeriodResponse.kt
  src/main/kotlin/dnd11th/blooming/api/service/guide/provider/StaticPlantSimpleMessageProvider.kt
  src/main/kotlin/dnd11th/blooming/api/service/guide/provider/WaterDetailProvider.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/plant/Plant.kt
  src/test/kotlin/dnd11th/blooming/api/service/myplant/MyPlantServiceTest.kt
Labels: 🧹 chore

#84 [BLOOM-083] 내 식물 등록/수정 방법 변경
  src/main/kotlin/dnd11th/blooming/api/controller/myplant/MyPlantController.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantCreateDto.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantModifyRequest.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantSaveRequest.kt
  src/main/kotlin/dnd11th/blooming/api/service/myplant/MyPlantService.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/MyPlant.kt
  src/test/kotlin/dnd11th/blooming/api/controller/myplant/MyPlantControllerTest.kt
  src/test/kotlin/dnd11th/blooming/api/controller/myplant/MyPlantControllerValidationTest.kt
  src/test/kotlin/dnd11th/blooming/api/service/myplant/MyPlantServiceTest.kt
Labels: 🔨 fix

#86 [BLOOM-085] 내 식물 상세조회 LocalDate 응답필드 추가
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantDetailResponse.kt
  src/test/kotlin/dnd11th/blooming/api/controller/myplant/MyPlantControllerTest.kt
Labels: 🌱 feat

#90 [BLOOM-089] 위치등록시 위치명 중복 예외 추가
  src/main/kotlin/dnd11th/blooming/api/controller/location/LocationApi.kt
  src/main/kotlin/dnd11th/blooming/api/service/location/LocationService.kt
  src/main/kotlin/dnd11th/blooming/common/exception/ErrorType.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/LocationRepository.kt
  src/test/kotlin/dnd11th/blooming/api/service/location/LocationServiceTest.kt
Labels: 🔨 fix

#92 [BLOOM-091] 날씨 메시지 API Interceptor 적용
  src/main/kotlin/dnd11th/blooming/api/controller/weather/WeatherMessageApi.kt
  src/main/kotlin/dnd11th/blooming/api/controller/weather/WeatherMessageController.kt
  src/main/kotlin/dnd11th/blooming/api/service/weather/WeatherService.kt
Labels: 🔨 fix

#94 [BLOOM-093] OAuth 로그 추가
  src/main/kotlin/dnd11th/blooming/api/service/user/oauth/IdTokenValidator.kt
  src/main/kotlin/dnd11th/blooming/client/oauth/OidcPublicKeys.kt
  src/main/kotlin/dnd11th/blooming/client/weather/WeatherResponse.kt
  src/main/kotlin/dnd11th/blooming/common/exception/ClientCallException.kt
  src/main/kotlin/dnd11th/blooming/common/exception/ErrorType.kt
  src/main/kotlin/dnd11th/blooming/common/exception/ExternalServerException.kt
  src/main/kotlin/dnd11th/blooming/common/exception/GlobalExceptionHandler.kt
Labels: 💊 refactor

#95 🚑 hotfix: update Dockerfile
  Dockerfile
Labels: 🔨 fix
