Repository dnd-side-project/dnd-11th-8-backend, pull requests merged in 2024-07, with the labels that each got.

#5 [BLOOM-002] 식물 저장, 전체 조회, 상세 조회 API 개발
  src/main/kotlin/dnd11th/blooming/api/controller/PlantController.kt
  src/main/kotlin/dnd11th/blooming/api/dto/PlantDetailResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/PlantResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/PlantSaveRequest.kt
  src/main/kotlin/dnd11th/blooming/api/dto/PlantSaveResponse.kt
  src/main/kotlin/dnd11th/blooming/api/service/PlantService.kt
  src/main/kotlin/dnd11th/blooming/common/exception/ErrorResponse.kt
  src/main/kotlin/dnd11th/blooming/common/exception/ExceptionCode.kt
  src/main/kotlin/dnd11th/blooming/common/exception/GlobalExceptionHandler.kt
  src/main/kotlin/dnd11th/blooming/common/exception/InvalidDateException.kt
  src/main/kotlin/dnd11th/blooming/common/exception/MyException.kt
  src/main/kotlin/dnd11th/blooming/common/exception/PlantNotFoundException.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/Plant.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/PlantRepository.kt
  src/test/kotlin/dnd11th/blooming/api/PlantControllerTest.kt
  src/test/kotlin/dnd11th/blooming/config/KotestConfig.kt
  src/test/kotlin/dnd11th/blooming/service/PlantServiceTest.kt
Labels: 🌱 feat

#11 [BLOOM-010] docker compose local db 설정
  docker/blooming-container/docker-compose.local.yml
Labels: 🧹 chore

#12 [BLOOM-009] 예외 응답 처리 리팩토링
  .github/pull_request_template.md
  src/main/kotlin/dnd11th/blooming/api/service/PlantService.kt
  src/main/kotlin/dnd11th/blooming/common/exception/ErrorResponse.kt
  src/main/kotlin/dnd11th/blooming/common/exception/ErrorType.kt
  src/main/kotlin/dnd11th/blooming/common/exception/ExceptionCode.kt
  src/main/kotlin/dnd11th/blooming/common/exception/GlobalExceptionHandler.kt
  src/main/kotlin/dnd11th/blooming/common/exception/InvalidDateException.kt
  src/main/kotlin/dnd11th/blooming/common/exception/MyException.kt
  src/main/kotlin/dnd11th/blooming/common/exception/NotFoundException.kt
  src/main/kotlin/dnd11th/blooming/common/exception/PlantNotFoundException.kt
  src/test/kotlin/dnd11th/blooming/api/PlantControllerTest.kt
  src/test/kotlin/dnd11th/blooming/service/PlantServiceTest.kt
Labels: 💊 refactor

#15 [BLOOM-007] 권한 인증 Interceptor 및 JWT 발급 로직 구현
  .github/workflows/ci.yml
  build.gradle.kts
  src/main/kotlin/dnd11th/blooming/api/config/WebMvcConfig.kt
  src/main/kotlin/dnd11th/blooming/api/controller/UserController.kt
  src/main/kotlin/dnd11th/blooming/common/annotation/Secured.kt
  src/main/kotlin/dnd11th/blooming/common/interceptor/AuthInterceptor.kt
  src/main/kotlin/dnd11th/blooming/common/jwt/JwtConfig.kt
  src/main/kotlin/dnd11th/blooming/common/jwt/JwtProvider.kt
  src/main/kotlin/dnd11th/blooming/common/jwt/UserClaims.kt
  src/main/resources/application.yml
  src/test/kotlin/dnd11th/blooming/Dnd11th8BackendApplicationTests.kt
  src/test/kotlin/dnd11th/blooming/api/PlantControllerTest.kt
  src/test/resources/application-test.yml
Labels: 🌱 feat

#13 [BLOOM-006] 알림속성 개발
  src/main/kotlin/dnd11th/blooming/api/controller/MyPlantController.kt
  src/main/kotlin/dnd11th/blooming/api/controller/PlantController.kt
  src/main/kotlin/dnd11th/blooming/api/dto/MyPlantDetailResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/MyPlantResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/MyPlantSaveRequest.kt
  src/main/kotlin/dnd11th/blooming/api/dto/MyPlantSaveResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/PlantDetailResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/PlantResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/PlantSaveRequest.kt
  src/main/kotlin/dnd11th/blooming/api/dto/PlantSaveResponse.kt
  src/main/kotlin/dnd11th/blooming/api/service/MyPlantService.kt
  src/main/kotlin/dnd11th/blooming/api/service/PlantService.kt
  src/main/kotlin/dnd11th/blooming/common/exception/ErrorType.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/Alarm.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/MyPlant.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/MyPlantRepository.kt
  src/test/kotlin/dnd11th/blooming/api/PlantControllerTest.kt
  src/test/kotlin/dnd11th/blooming/service/PlantServiceTest.kt
Labels: 🌱 feat

#22 [BLOOM-021] CODEOWNERS & Banner.txt 설정
  .github/CODEOWNERS
  src/main/resources/banner.txt
Labels: 🧹 chore

#20 [BLOOM-016] LoginUser 어노테이션 및 해당 HandlerMethodArgumentResolver 구현
  src/main/kotlin/dnd11th/blooming/api/controller/UserController.kt
  src/main/kotlin/dnd11th/blooming/common/annotation/LoginUser.kt
  src/main/kotlin/dnd11th/blooming/common/interceptor/AuthInterceptor.kt
  src/main/kotlin/dnd11th/blooming/common/jwt/JwtProvider.kt
  src/main/kotlin/dnd11th/blooming/common/resolver/LoginUserArgumentResolver.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/User.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/UserClaims.kt
  src/test/kotlin/dnd11th/blooming/common/jwt/JwtProviderTest.kt
Labels: 🌱 feat

#19 [BLOOM-014] 알림 API 개발
  src/main/kotlin/dnd11th/blooming/api/controller/MyPlantController.kt
  src/main/kotlin/dnd11th/blooming/api/dto/AlarmModifyRequest.kt
  src/main/kotlin/dnd11th/blooming/api/dto/AlarmResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/MyPlantResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/MyPlantSaveRequest.kt
  src/main/kotlin/dnd11th/blooming/api/dto/MyPlantSaveResponse.kt
  src/main/kotlin/dnd11th/blooming/api/service/MyPlantService.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/Alarm.kt
  src/test/kotlin/dnd11th/blooming/api/PlantControllerTest.kt
  src/test/kotlin/dnd11th/blooming/service/PlantServiceTest.kt
Labels: 🌱 feat
