Repository dnd-side-project/dnd-11th-8-backend, pull requests merged in 2024-09, with the labels that each got.

#97 [BLOOM-096] DeviceToken 등록 API 구현
  src/main/kotlin/dnd11th/blooming/api/config/SwaggerConfig.kt
  src/main/kotlin/dnd11th/blooming/api/controller/home/HomeApi.kt
  src/main/kotlin/dnd11th/blooming/api/controller/image/ImageApi.kt
  src/main/kotlin/dnd11th/blooming/api/controller/region/RegionApi.kt
  src/main/kotlin/dnd11th/blooming/api/controller/region/RegionController.kt
  src/main/kotlin/dnd11th/blooming/api/controller/user/DeviceTokenApi.kt
  src/main/kotlin/dnd11th/blooming/api/controller/user/DeviceTokenController.kt
  src/main/kotlin/dnd11th/blooming/api/controller/user/TokenApi.kt
  src/main/kotlin/dnd11th/blooming/api/controller/user/TokenController.kt
  src/main/kotlin/dnd11th/blooming/api/controller/user/UserApi.kt
  src/main/kotlin/dnd11th/blooming/api/controller/user/UserController.kt
  src/main/kotlin/dnd11th/blooming/api/controller/user/UserLoginApi.kt
  src/main/kotlin/dnd11th/blooming/api/controller/weather/WeatherMessageApi.kt
  src/main/kotlin/dnd11th/blooming/api/controller/weather/WeatherMessageController.kt
  src/main/kotlin/dnd11th/blooming/api/dto/region/RegionResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/user/DeviceTokenRequest.kt
  src/main/kotlin/dnd11th/blooming/api/service/user/DeviceTokenService.kt
  src/main/kotlin/dnd11th/blooming/common/annotation/Secured.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/devicetoken/DeviceToken.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/devicetoken/DeviceTokenRepository.kt
Labels: 🌱 feat

#104 [BLOOM-103] 식물 종류 검색 핫픽스
  src/main/kotlin/dnd11th/blooming/common/util/UpdatePlantDecomposedKorName.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/plant/Plant.kt
Labels: 🔨 fix

#102 [BLOOM-101] 내 식물 전체 조회 api 수정
  src/main/kotlin/dnd11th/blooming/api/controller/myplant/MyPlantApi.kt
  src/main/kotlin/dnd11th/blooming/api/controller/myplant/MyPlantController.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantIdWithImageUrl.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantQueryCreteria.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/MyPlantResponse.kt
  src/main/kotlin/dnd11th/blooming/api/service/myplant/MyPlantService.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/ImageRepository.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/myplant/MyPlantQueryDslRepository.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/myplant/MyPlantQueryDslRepositoryImpl.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/myplant/MyPlantRepository.kt
  src/test/kotlin/dnd11th/blooming/api/controller/myplant/MyPlantControllerTest.kt
  src/test/kotlin/dnd11th/blooming/api/service/myplant/MyPlantServiceIntegrationTest.kt
  src/test/kotlin/dnd11th/blooming/api/service/myplant/MyPlantServiceTest.kt
Labels: 🔨 fix

#105 [BLOOM-100] 로그아웃 및 RefershToken을 통한 토큰 재발급 구현
  build.gradle.kts
  docker/blooming-container/docker-compose.local.yml
  src/main/kotlin/dnd11th/blooming/api/controller/user/TokenApi.kt
  src/main/kotlin/dnd11th/blooming/api/controller/user/UserLoginApi.kt
  src/main/kotlin/dnd11th/blooming/api/controller/user/UserLoginController.kt
  src/main/kotlin/dnd11th/blooming/api/dto/user/SocialLoginResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/user/TokenRequest.kt
  src/main/kotlin/dnd11th/blooming/api/dto/user/TokenResponse.kt
  src/main/kotlin/dnd11th/blooming/api/service/user/LogoutService.kt
  src/main/kotlin/dnd11th/blooming/api/service/user/SocialLoginService.kt
  src/main/kotlin/dnd11th/blooming/api/service/user/TokenService.kt
  src/main/kotlin/dnd11th/blooming/api/service/user/UserRegisterService.kt
  src/main/kotlin/dnd11th/blooming/common/exception/ErrorType.kt
  src/main/kotlin/dnd11th/blooming/common/holder/InstantHolder.kt
  src/main/kotlin/dnd11th/blooming/common/holder/SystemInstantHolder.kt
  src/main/kotlin/dnd11th/blooming/common/jwt/JwtProvider.kt
  src/main/kotlin/dnd11th/blooming/common/resolver/LoginUserArgumentResolver.kt
  src/main/kotlin/dnd11th/blooming/domain/config/RedisConfig.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/refreshtoken/RefreshToken.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/user/UserClaims.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/token/RefreshTokenRedisRepository.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/token/RefreshTokenRepository.kt
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/test/resources/application-test.yml
Labels: 🌱 feat

#109 [BLOOM-108] 알림 주기 미설정시 자동으로 추천주기로 설정
  src/main/kotlin/dnd11th/blooming/api/controller/myplant/MyPlantController.kt
  src/main/kotlin/dnd11th/blooming/api/dto/guide/PlantRecommendedPeriodResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/AlarmModifyDto.kt
  src/main/kotlin/dnd11th/blooming/api/dto/myplant/AlarmModifyRequest.kt
  src/main/kotlin/dnd11th/blooming/api/service/myplant/MyPlantService.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/Alarm.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/MyPlant.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/plant/Plant.kt
  src/test/kotlin/dnd11th/blooming/api/controller/myplant/MyPlantControllerTest.kt
  src/test/kotlin/dnd11th/blooming/api/service/myplant/MyPlantServiceTest.kt
Labels: 🌱 feat

#106 [BLOOM-072] 물 주기 알림 스케줄러 작성
  build.gradle.kts
  src/main/kotlin/dnd11th/blooming/batch/BatchConfig.kt
  src/main/kotlin/dnd11th/blooming/batch/NotificationScheduler.kt
  src/main/kotlin/dnd11th/blooming/batch/PlantNotificationJobConfig.kt
  src/main/kotlin/dnd11th/blooming/batch/PlantNotificationProcessor.kt
  src/main/kotlin/dnd11th/blooming/batch/PlantNotificationReader.kt
  src/main/kotlin/dnd11th/blooming/batch/PlantNotificationWriter.kt
  src/main/kotlin/dnd11th/blooming/batch/UserPlantDto.kt
  src/main/kotlin/dnd11th/blooming/client/fcm/FcmService.kt
  src/main/kotlin/dnd11th/blooming/client/fcm/FcmServiceImpl.kt
  src/main/kotlin/dnd11th/blooming/client/fcm/PushNotification.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/plant/GrowTemperature.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/user/AlarmTime.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/myplant/MyPlantQueryDslRepository.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/myplant/MyPlantQueryDslRepositoryImpl.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/myplant/MyPlantRepository.kt
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/schema-batch.sql
  src/test/resources/application-test.yml
Labels: 🌱 feat

#110 [BLOOM-040] 온보딩 api 개발
  src/main/kotlin/dnd11th/blooming/api/controller/onboard/OnboardApi.kt
  src/main/kotlin/dnd11th/blooming/api/controller/onboard/OnboardController.kt
  src/main/kotlin/dnd11th/blooming/api/dto/onboard/AnswerResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/onboard/OnboardResultRequest.kt
  src/main/kotlin/dnd11th/blooming/api/dto/onboard/OnboardResultResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/onboard/OnboardScriptResponse.kt
  src/main/kotlin/dnd11th/blooming/api/dto/onboard/QuestionResponse.kt
  src/main/kotlin/dnd11th/blooming/api/service/onboard/OnboardService.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/onboard/OnboardingAnswer.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/onboard/OnboardingAnswerToResult.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/onboard/OnboardingQuestion.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/onboard/OnboardingResult.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/onboard/OnboardAnswerQueryDslRepository.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/onboard/OnboardAnswerQueryDslRepositoryImpl.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/onboard/OnboardAnswerRepository.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/onboard/OnboardAnswerToResultRepository.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/onboard/OnboardQuestionRepository.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/onboard/OnboardResultRepository.kt
  src/test/kotlin/dnd11th/blooming/api/service/onboard/OnboardServiceIntegrationTest.kt
Labels: 🌱 feat

#113 [BLOOM-111] 회원탈퇴 기능 구현
  src/main/kotlin/dnd11th/blooming/api/controller/user/UserApi.kt
  src/main/kotlin/dnd11th/blooming/api/controller/user/UserController.kt
  src/main/kotlin/dnd11th/blooming/api/service/user/UserWithdrawService.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/ImageRepository.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/LocationRepository.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/myplant/MyPlantRepository.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/user/UserOauthRepository.kt
Labels: 🌱 feat

#116 [BLOOM-112] 디바이스 토큰 삭제 구현
  src/main/kotlin/dnd11th/blooming/api/controller/user/DeviceTokenApi.kt
  src/main/kotlin/dnd11th/blooming/api/controller/user/DeviceTokenController.kt
  src/main/kotlin/dnd11th/blooming/api/service/user/DeviceTokenService.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/devicetoken/DeviceToken.kt
  src/main/kotlin/dnd11th/blooming/domain/entity/user/User.kt
  src/main/kotlin/dnd11th/blooming/domain/repository/devicetoken/DeviceTokenRepository.kt
Labels: 🌱 feat

#121 🚑 [hotfix]: deploy.yml fcm path 수정
  .github/workflows/deploy.yml
Labels: 🔨 fix

#125 🚑 hotfix: fcm 폴더 생성 path 수정
  .github/workflows/deploy.yml
Labels: 🔨 fix

#123 [BLOOM-122] 전역 예외처리 추가
  api/src/main/kotlin/dnd11th/blooming/api/controller/exception/GlobalExceptionHandler.kt
  common/src/main/kotlin/dnd11th/blooming/common/exception/ErrorType.kt
Labels: 🌱 feat

#127 [BLOOM-124] 모니터링용 prometheus, loki4j 의존성 추가 및 설정
  api/build.gradle.kts
  api/src/main/resources/application.yml
  monitoring/build.gradle.kts
  monitoring/src/main/resources/logback-spring.xml
  monitoring/src/main/resources/monitoring.yml
  settings.gradle.kts
Labels: 🌱 feat

#129 [BLOOM-128] 이미지 삭제 api 수정
  api/src/main/kotlin/dnd11th/blooming/api/controller/image/ImageApi.kt
  api/src/main/kotlin/dnd11th/blooming/api/controller/image/ImageController.kt
  api/src/main/kotlin/dnd11th/blooming/api/dto/image/ImageDeleteRequest.kt
  api/src/main/kotlin/dnd11th/blooming/api/service/image/ImageService.kt
  domain/core/src/main/kotlin/dnd11th/blooming/core/repository/image/ImageRepository.kt
Labels: 🔨 fix

#130 ♻️ refactor: add redis host env
  .github/workflows/deploy.yml
  Dockerfile
  domain/redis/src/main/resources/redis-prod.yml
Labels: 💊 refactor

#131 🚑 fix: fix deploy.yml
  .github/workflows/deploy.yml
Labels: 🔨 fix

#133 📄 docs: Create README.md
  README.md
Labels: 📚 docs

#132 [BLOOM-107] 기상청 API 배치 시스템 구현
  api/src/main/kotlin/dnd11th/blooming/api/controller/weather/WeatherMessageController.kt
  api/src/main/kotlin/dnd11th/blooming/api/dto/weather/WeatherMessageResponse.kt
  api/src/main/kotlin/dnd11th/blooming/api/service/weather/WeatherMessage.kt
  api/src/main/kotlin/dnd11th/blooming/api/service/weather/WeatherService.kt
  batch/build.gradle.kts
  batch/src/main/kotlin/dnd11th/blooming/Dnd11th8BackendBatchApplication.kt
  batch/src/main/kotlin/dnd11th/blooming/batch/BatchConfig.kt
  batch/src/main/kotlin/dnd11th/blooming/batch/PlantNotificationJobConfig.kt
  batch/src/main/kotlin/dnd11th/blooming/batch/controller/DailyWeatherCallController.kt
  batch/src/main/kotlin/dnd11th/blooming/batch/weather/WeatherCareMessageJobConfig.kt
  batch/src/main/kotlin/dnd11th/blooming/batch/weather/WeatherCareMessageReader.kt
  batch/src/main/kotlin/dnd11th/blooming/batch/weather/WeatherCareMessageScheduler.kt
  batch/src/main/kotlin/dnd11th/blooming/batch/weather/WeatherCareMessageWriter.kt
  batch/src/main/resources/application.yml
  batch/src/main/resources/batch-local.yml
  batch/src/main/resources/batch-prod.yml
  domain/core/src/main/resources/core-prod.yml
  domain/redis/src/main/kotlin/dnd11th/blooming/redis/config/RedisConfig.kt
  domain/redis/src/main/kotlin/dnd11th/blooming/redis/entity/weather/WeatherCareMessage.kt
  domain/redis/src/main/kotlin/dnd11th/blooming/redis/entity/weather/WeatherCareMessageType.kt
  domain/redis/src/main/kotlin/dnd11th/blooming/redis/repository/weather/WeatherCareMessageRedisRepository.kt
  domain/redis/src/main/kotlin/dnd11th/blooming/redis/repository/weather/WeatherCareMessageRepository.kt
Labels: 🌱 feat, 💊 refactor
